# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch: 
    inputs:
      environment:        
        description: 'Environment'
        required: true
        default: 'STAGE CLOUD'
        type: choice
        options:
          - QA
          - QA CLOUD
          - STAGE CLOUD
          - UAT
          - STAGE
          - DEV
      tag:        
        description: 'Provide tag to run the test suite'
        required: true
        default: '@US1272281'
        type: String        
      sauceUsername:        
        description: 'Sauce Username'
        required: true
        default: ''
        type: String
      sauceKey:        
        description: 'Sauce Key'
        required: true
        default: ''
        type: String

jobs:
  Test_build1:
    runs-on: ubuntu-latest
    
    env:
      Environment: ${{github.event.inputs.environment}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Run Test
        run: mvn clean test -U -P Smoke -D"sonar.skip"=true -D"cucumber.options"="--tags ${{github.event.inputs.tag}}"
        
      - name: Archive Test Report
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'Test-report'
          path: ExtentReports/ExtentReport.html
